### ISSUE TITLE
IE11, on Edge or 10 mode.

### ISSUE THREAD

**Issue by johnnliu** [jdanyow/aurelia-converters-sample#2]
HTML1300: Navigation occurred.
File: about:blank
HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
File: about:blank, Line: 1, Column: 1
HTML1300: Navigation occurred.
File: fp2RwDvm6q
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: binding-with-value-converters-in-aurelia, Line: 135, Column: 4
HTML1501: Unexpected end of file.
File: binding-with-value-converters-in-aurelia, Line: 184, Column: 1
HTML1521: Unexpected "< /body>" or end of file. All open elements should be closed before the end of the document.
File: binding-with-value-converters-in-aurelia, Line: 184, Column: 1
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: binding-with-value-converters-in-aurelia
HTML1300: Navigation occurred.
File: aurelia-converters-sample
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
File: binding-with-value-converters-in-aurelia
INFO [aurelia] Aurelia Starting
DEBUG [aurelia] Loading plugin github:aurelia/templating-binding@0.8.5.
DEBUG [aurelia] Installed plugin github:aurelia/templating-binding@0.8.5.
DEBUG [aurelia] Loading plugin github:aurelia/templating-resources@0.8.8.
DEBUG [aurelia] Installed plugin github:aurelia/templating-resources@0.8.8.
DEBUG [aurelia] Loading plugin github:aurelia/history-browser@0.2.3.
DEBUG [aurelia] Installed plugin github:aurelia/history-browser@0.2.3.
DEBUG [aurelia] Loading plugin github:aurelia/templating-router@0.9.2.
DEBUG [aurelia] Installed plugin github:aurelia/templating-router@0.9.2.
DEBUG [aurelia] Loading plugin github:aurelia/event-aggregator@0.2.2.
DEBUG [aurelia] Installed plugin github:aurelia/event-aggregator@0.2.2.
DEBUG [aurelia] Loading plugin ./resources/index.
DEBUG [aurelia] Installed plugin ./resources/index.
DEBUG [templating] importing resources for resources/example.html 
   "DEBUG [templating] importing resources for resources/example.html"
   [
      length: 0
   ]

DEBUG [templating] importing resources for resources/column.html 
   "DEBUG [templating] importing resources for resources/column.html"
   [
      length: 0
   ]

DEBUG [templating] importing resources for resources/file.html 
   "DEBUG [templating] importing resources for resources/file.html"
   [
      length: 0
   ]

INFO [aurelia] Aurelia Started
DEBUG [templating] importing resources for dist/app.html 
   "DEBUG [templating] importing resources for dist/app.html"
   [
      length: 0
   ]

SEC7118: XMLHttpRequest for https://api.github.com/orgs/aurelia/repos required Cross Origin Resource Sharing (CORS).
File: aurelia-converters-sample
DEBUG [templating] importing resources for examples/1/view.html 
   "DEBUG [templating] importing resources for examples/1/view.html"
   [
      length: 0
   ]

DEBUG [templating] importing resources for examples/2/view.html 
   "DEBUG [templating] importing resources for examples/2/view.html"
   [
      length: 0
   ]

Potentially unhandled rejection [1] TypeError: Unable to get property 'insertBefore' of undefined or null reference
   at compileNode (Unknown script code:113:21)
   at compileNode (Unknown script code:121:21)
   at compile (Unknown script code:93:15)
   at Anonymous function (Unknown script code:56:19)
   at O (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7449)
   at K (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7036)
   at y.prototype.when (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:10248)
   at v.prototype.run (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:9282)
   at a.prototype._drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1748)
   at drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1415)
DEBUG [templating] importing resources for examples/3/view.html examples/3/date-format,examples/3/currency-format
   "DEBUG [templating] importing resources for examples/3/view.html"
   [
      0: "examples/3/date-format",
      1: "examples/3/currency-format",
      length: 2
   ]

DEBUG [templating] importing resources for examples/4/view.html examples/4/date-format,examples/4/number-format
   "DEBUG [templating] importing resources for examples/4/view.html"
   [
      0: "examples/4/date-format",
      1: "examples/4/number-format",
      length: 2
   ]

DEBUG [templating] importing resources for examples/5/view.html examples/5/number-format
   "DEBUG [templating] importing resources for examples/5/view.html"
   [
      0: "examples/5/number-format",
      length: 1
   ]

DEBUG [templating] importing resources for examples/7/view.html examples/7/rgb-to-hex
   "DEBUG [templating] importing resources for examples/7/view.html"
   [
      0: "examples/7/rgb-to-hex",
      length: 1
   ]

Potentially unhandled rejection [2] TypeError: Unable to get property 'insertBefore' of undefined or null reference
   at compileNode (Unknown script code:113:21)
   at compileNode (Unknown script code:121:21)
   at compile (Unknown script code:93:15)
   at Anonymous function (Unknown script code:56:19)
   at O (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7449)
   at K (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7036)
   at y.prototype.when (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:10248)
   at v.prototype.run (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:9282)
   at a.prototype._drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1748)
   at drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1415)
Potentially unhandled rejection [3] TypeError: Unable to get property 'insertBefore' of undefined or null reference
   at compileNode (Unknown script code:113:21)
   at compileNode (Unknown script code:121:21)
   at compile (Unknown script code:93:15)
   at Anonymous function (Unknown script code:56:19)
   at O (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7449)
   at K (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7036)
   at y.prototype.when (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:10248)
   at v.prototype.run (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:9282)
   at a.prototype._drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1748)
   at drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1415)
Potentially unhandled rejection [4] TypeError: Unable to get property 'insertBefore' of undefined or null reference
   at compileNode (Unknown script code:113:21)
   at compileNode (Unknown script code:121:21)
   at compile (Unknown script code:93:15)
   at Anonymous function (Unknown script code:56:19)
   at O (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7449)
   at K (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7036)
   at y.prototype.when (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:10248)
   at v.prototype.run (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:9282)
   at a.prototype._drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1748)
   at drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1415)
Potentially unhandled rejection [5] TypeError: Unable to get property 'insertBefore' of undefined or null reference
   at compileNode (Unknown script code:113:21)
   at compileNode (Unknown script code:121:21)
   at compile (Unknown script code:93:15)
   at Anonymous function (Unknown script code:56:19)
   at O (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7449)
   at K (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:7036)
   at y.prototype.when (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:10248)
   at v.prototype.run (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:9282)
   at a.prototype._drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1748)
   at drain (http://jdanyow.github.io/aurelia-converters-sample/jspm_packages/es6-module-loader.js:7:1415)
DEBUG [templating] importing resources for examples/6/view.html examples/6/sort,examples/6/take
   "DEBUG [templating] importing resources for examples/6/view.html"
   [
      0: "examples/6/sort",
      1: "examples/6/take",
      length: 2
   ]

**Comment by johnnliu** [comment]
http://jdanyow.github.io/aurelia-converters-sample/

Simple binding examples works.

Everything after Binding Dates and Numbers doesn't.

**Comment by jdanyow** [comment]
@johnnliu thanks for the details!  this will be fixed in next week Aurelia build

**Comment by jdanyow** [comment]
fixed
